<a href="https://colab.research.google.com/github/Lokeshpolice/Lokeshpolice/blob/main/Lab_3_Neural_Network_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def perceptron(inputs, weights, threshold):
  # Calculate the weighted sum
  weighted_sum = 0
  for i in range(len(inputs)):
    weighted_sum += inputs[i] * weights[i]

  # Apply the step function
  if weighted_sum > threshold:
    return 1 # Fire! (Go for a walk)
  else:
    return 0 # Don't fire. (Stay inside)

# Inputs: [is_sunny, is_warm]
inputs = [1, 1] # It's sunny and warm

# Weights: Let's say warmth is more important than sunniness
weights = [0.5, 0.8]

# Threshold: Our decision boundary
threshold = 1.0

output = perceptron(inputs, weights, threshold)
print(f"Decision: {output}")

Decision: 1


Part 3: How a Neural Network Learns

In [12]:
import numpy as np

# The Sigmoid function and its derivative
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

# Our training data
training_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T # .T transposes it to a column

# Seed the random numbers to make calculations deterministic (good for debugging)
np.random.seed(1)

# Initialize weights randomly with mean 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights:')
print(synaptic_weights)

for iteration in range(10000):
  # Step 1: Forward Propagation
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights)) # Make a guess

  # Step 2: Calculate Loss (the error)
  error = training_outputs - outputs

  # Step 3: Backward Propagation & Weight Update
  adjustments = error * sigmoid_derivative(outputs) # Find the 'blame'
  synaptic_weights += np.dot(input_layer.T, adjustments) # Nudge the weights

print('Synaptic weights after training:')
print(synaptic_weights)

print('\nOutputs after training:')
print(outputs)

Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]

Outputs after training:
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]


my turn

What happens if you change the `inputs` to `[0, 1]` (not sunny, but warm)? Does the robot still decide to go for a walk?

In [10]:
def perceptron(inputs, weights, threshold):
  # Calculate the weighted sum
  weighted_sum = 0
  for i in range(len(inputs)):
    weighted_sum += inputs[i] * weights[i]

  # Apply the step function
  if weighted_sum > threshold:
    return 1 # Fire! (Go for a walk)
  else:
    return 0 # Don't fire. (Stay inside)

# Inputs: [is_sunny, is_warm]
inputs = [0, 1] # It's sunny and warm

# Weights: Let's say warmth is more important than sunniness
weights = [0.5, 0.8]

# Threshold: Our decision boundary
threshold = 1.0

output = perceptron(inputs, weights, threshold)
print(f"Decision: {output}")

Decision: 0


What happens if you change the `weights` to `[0.8, 0.1]` making sunniness more important?

In [3]:
def perceptron(inputs, weights, threshold):
  # Calculate the weighted sum
  weighted_sum = 0
  for i in range(len(inputs)):
    weighted_sum += inputs[i] * weights[i]

  # Apply the step function
  if weighted_sum > threshold:
    return 1 # Fire! (Go for a walk)
  else:
    return 0 # Don't fire. (Stay inside)

# Inputs: [is_sunny, is_warm]
inputs = [1, 1] # It's sunny and warm

# Weights: Let's say warmth is more important than sunniness
weights = [0.8, 0.1]

# Threshold: Our decision boundary
threshold = 1.0

output = perceptron(inputs, weights, threshold)
print(f"Decision: {output}")

Decision: 0


What happens if you increase the `threshold` to `1.5`?

In [4]:
def perceptron(inputs, weights, threshold):
  # Calculate the weighted sum
  weighted_sum = 0
  for i in range(len(inputs)):
    weighted_sum += inputs[i] * weights[i]

  # Apply the step function
  if weighted_sum > threshold:
    return 1 # Fire! (Go for a walk)
  else:
    return 0 # Don't fire. (Stay inside)

# Inputs: [is_sunny, is_warm]
inputs = [1, 1] # It's sunny and warm

# Weights: Let's say warmth is more important than sunniness
weights = [0.5, 0.8]

# Threshold: Our decision boundary
threshold = 1.5

output = perceptron(inputs, weights, threshold)
print(f"Decision: {output}")

Decision: 0


Change the number of iterations in the `range()` from `10000` to `100`. Run it. Are the final outputs as good?

In [17]:
import numpy as np

# The Sigmoid function and its derivative
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

# Our training data
training_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T # .T transposes it to a column

# Seed the random numbers to make calculations deterministic (good for debugging)
np.random.seed(1)

# Initialize weights randomly with mean 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights:')
print(synaptic_weights)

for iteration in range(100):
  # Step 1: Forward Propagation
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights)) # Make a guess

  # Step 2: Calculate Loss (the error)
  error = training_outputs - outputs

  # Step 3: Backward Propagation & Weight Update
  adjustments = error * sigmoid_derivative(outputs) # Find the 'blame'
  synaptic_weights += np.dot(input_layer.T, adjustments) # Nudge the weights

print('Synaptic weights after training:')
print(synaptic_weights)

print('\nOutputs after training:')
print(outputs)

Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training:
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]

Outputs after training:
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


Change it to `100000`. Do the outputs get even closer to 0 and 1?

In [14]:
import numpy as np

# The Sigmoid function and its derivative
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

# Our training data
training_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T # .T transposes it to a column

# Seed the random numbers to make calculations deterministic (good for debugging)
np.random.seed(1)

# Initialize weights randomly with mean 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights:')
print(synaptic_weights)

for iteration in range(100):
  # Step 1: Forward Propagation
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights)) # Make a guess

  # Step 2: Calculate Loss (the error)
  error = training_outputs - outputs

  # Step 3: Backward Propagation & Weight Update
  adjustments = error * sigmoid_derivative(outputs) # Find the 'blame'
  synaptic_weights += np.dot(input_layer.T, adjustments) # Nudge the weights

print('Synaptic weights after training:')
print(synaptic_weights)

print('\nOutputs after training:')
print(outputs)

Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training:
[[ 4.62128737]
 [-0.20338466]
 [-2.09325311]]

Outputs after training:
[[0.11035029]
 [0.91041229]
 [0.92564882]
 [0.09193919]]


Inside the loop, right after the weights are updated, add `if iteration % 1000 == 0: print(np.mean(np.abs(error)))`. This will print the average error every 1000 steps. You should see the error getting smaller and smaller!

In [ ]:
import numpy as np

# The Sigmoid function and its derivative
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

# Our training data
training_inputs = np.array([[0, 0, 1],
                            [1, 1, 1],
                            [1, 0, 1],
                            [0, 1, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T # .T transposes it to a column

# Seed the random numbers to make calculations deterministic (good for debugging)
np.random.seed(1)

# Initialize weights randomly with mean 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights:')
print(synaptic_weights)

for iteration in range(10000):
  # Step 1: Forward Propagation
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights)) # Make a guess

  # Step 2: Calculate Loss (the error)
  error = training_outputs - outputs

  # Step 3: Backward Propagation & Weight Update
  adjustments = error * sigmoid_derivative(outputs) # Find the 'blame'
  synaptic_weights += np.dot(input_layer.T, adjustments) # Nudge the weights
  if iteration %1000 == 0:
    print("\n", np.mean(np.abs(error)))


print('\nSynaptic weights after training:')
print(synaptic_weights)

print('\nOutputs after training:')
print(outputs)

Part 5: Your First Neural Network Mission

In [19]:
import numpy as np

# The Sigmoid function and its derivative
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

# Our training data
# Inputs: [Test 1, Test 2, Test 3]
training_inputs = np.array([[0, 1, 1], [1, 0, 0], [0, 1, 0], [1, 1, 0]])
training_input = np.array (([1, 1, 1]))
# Outputs: [Is Faulty?]
training_outputs = np.array([[0, 1, 0, 1]]).T
# Seed the random numbers to make calculations deterministic (good for debugging)
np.random.seed(1)

# Initialize weights randomly with mean 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights:')
print(synaptic_weights)

for iteration in range(20000):
  # Step 1: Forward Propagation
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights)) # Make a guess

  # Step 2: Calculate Loss (the error)
  error = training_outputs - outputs

  # Step 3: Backward Propagation & Weight Update
  adjustments = error * sigmoid_derivative(outputs) # Find the 'blame'
  synaptic_weights += np.dot(input_layer.T, adjustments) # Nudge the weights

print('Synaptic weights after training:')
print(synaptic_weights)

print('\nOutputs after training:')
print(outputs)



Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training:
[[ 9.66500594]
 [-4.73511652]
 [-1.94393347]]

Outputs after training:
[[0.00125543]
 [0.99993653]
 [0.0087052 ]
 [0.99282437]]


Among the weights, the second weight has the largest value.